pyca/infra

.travis.yml
We are currently developing with branches rather than fork + branch so
we're doing a lot of pointless Travis builds. Let's just build master
for now.
=> only build master on travis

runners/jessie-libressl/hooks/build
This is tested and working against the branch. See: https://hub.docker.com/r/pyca/cryptography-runner-jessie-libressl/builds/
=> add a docker hub hooks file to build libressl tags

ansible/systemd/jenkins.service
On Windows the path limit is 260 characters. The jenkins branch API
adds a suffix that by default can be up to 80 characters, which puts us
over the limit on some of our longer file names. This change should
prevent that problem...for now
=> add a PATH_MAX to prevent failures due to path length on windows

runners/fedora/Dockerfile
See: https://ci.cryptography.io/blue/organizations/jenkins/pyca%2Fcryptography/detail/PR-3680/10/pipeline/72#step-928-log-382
=> adding findutils because codecov expects it to be available

config.json, runners/stretch-openssl-master/Dockerfile
I don't want to add this into CI (yet), but it'd be nice to have a container that contains a daily OpenSSL master build that we can test with as we desire.
If we decide we want to merge this we should not merge until after I create the dockerhub repo
=> add an openssl master container for easier testing

config.json, runners/alpine/Dockerfile
With the upcoming manylinux1 support we're going to see a swift shift to
the most common compilation issues coming from alpine (which is not
manylinux1 compatible). Compounding that it defaults to libressl.
We should test against it (and maybe drop the libre 2.5.3 jessie
builder)
=> add an alpine runner

runners/jessie-libressl/Dockerfile
that's possibly a bug that will be fixed, but in the mean time we're broken and this will work either way.
=> docker changed ADD in 17.06 so that it auto-decompresses

cryptography-manylinux1/install_openssl.sh
no-shared implies no-dynamic-engine but I want to explicitly call it out in case we switch back to shared libs for some reason in the future
refs https://github.com/pyca/cryptography/issues/3810 and https://github.com/pyca/cryptography/issues/3804
=> switch to building static libs for cryptography wheels

external-projects/Jenkinsfile-cffi-wheel-builder
manylinux1 no longer ships python 2.6 binaries.
=> remove python 2.6 manylinux builder for cffi

cryptography-manylinux1/Dockerfile
this allows cryptography's wheel scripts to confirm that wheels are built with noexecstack
refs pyca/cryptography#4130
=> add execstack to the container

external-projects/Jenkinsfile-cffi-wheel-builder
cffi can't use the limited API. A fact I knew but forgot so do I really get to say I knew it?
=> Revert cffi py_limited_api work

cryptography-manylinux1/Dockerfile, cryptography-manylinux1/install_libffi.sh
we need this to work around the build isolation that prevents pip wheel from using the cffi wheels
=> add libffi to cryptography manylinux1 builders

windows/openssl/Dockerfile, windows/py27/Dockerfile, windows/py3/Dockerfile, windows/py34/Dockerfile, windows/py35/Dockerfile
azure pipelines is going to be caching 1809 apparently, see
https://github.com/microsoft/azure-pipelines-image-generation/blob/74573d89ae49e6be3e507c5af91758dbb2c114c9/images/win/scripts/Installers/Vs2019/Update-DockerImages.ps1
=> use 1809 instead of ltsc2019

windows/py3/Dockerfile, windows/py3/install_everything.ps1
For some bizarre reason docker layers bloat windows docker images **horribly**. In testing this PR made my (server 2016-based) image 1.8GB smaller (uncompressed).
Docker formerly checked our exit codes and powershell won't fail a script just because an exe had a non-zero exit code (since windows exit codes are not standardized) so we have to do a bunch of extra error code checking to make sure we properly fail.
=> try to shrink our windows docker py3 image

windows/openssl/Dockerfile, windows/openssl/vs.bat
Verified by running a build already. Hooray we can compile again. Yes this is ridiculous, but hey apparently we **don't** need .NET.
=> Fix Windows OpenSSL building

windows/openssl/build_openssl.bat, windows/openssl/build_openssl_win32_2010.bat, windows/openssl/build_openssl_win32_2015.bat, windows/openssl/build_openssl_win64_2010.bat, windows/openssl/build_openssl_win64_2015.bat, windows/openssl/vs.bat
This is really just because we need nmake and previously we didn't have it so the CI passed by failing! So this also adds a bunch of error checking we didn't have previously (thanks cmd.exe)
=> Switch back to VS2017 for windows openssl

external-projects/cffi-wheel-builder.yml
From the 3.8 changelog:
> Default sys.abiflags became an empty string: the m flag for pymalloc became useless (builds with and without pymalloc are ABI compatible) and so has been removed. (Contributed by Victor Stinner in bpo-36707.)
=> Remove pymalloc build tag from python3.8 wheel

.github/workflows/build-macos-openssl.yml
We need to build our own macOS OpenSSL now. We need this because `-mmacosx-version-min` is a flag we must pass when building OpenSSL to avoid getting symbols that won't work in older macOS. We miraculously got away with not doing this for many years, but that was sheer luck. Our luck has run out.
We already passed this flag to the cryptography wheel build itself, but homebrew doesn't pass this since they build bottles on a per-macOS basis. Prior to 10.15 this didn't matter because we weren't building anything that caused macOS to link in symbols that didn't work on older macOS, but the addition of `____chkstk_darwin` caused this bug to manifest on Catalina.
This isn't homebrew's fault, but our situation is an edge case (from homebrew's perspective) where we need to ship binaries built on …
=> macos openssl builder time

.github/workflows/build-docker-images.yml, runners/debian/Dockerfile
I've added the focal dockerhub repo. We can remove jessie/trusty/xenial after this merges. We do not use them in cryptography's CI any more.
=> build focal image, remove unused trusty, xenial, jessie

.github/workflows/build-docker-images.yml, cryptography-manylinux/Dockerfile-manylinux2014_aarch64
Containers not supported Arm64
- Alpine Linux -- missing rustup precompiled binary on rust-lang site
- manylinux1 -- x86 only
- manylinux2010 -- x86 only
Remaining containers are built using buildx inside github actions to push a manifest to the docker repository to allow tags to contain multiple architectures.  Doing a `docker pull` on x86 or Arm64 machines will pull the expected container.
Tested in my own docker account and see all the containers with both x86 and arm64 hashes.
=> Build Arm64 container for Manylinux2014_aarch64

.github/workflows/build-macos-openssl.yml
Will require an immediate follow up PR in pyca/cryptography
=> Include the architecture in the macOS OpenSSL artifact name

cryptography-manylinux/Dockerfile-manylinux1
We won't be building manylinux1 images once we integrate rust, since recent rusts don't support glibc that old.
=> Don't install rust in the manylinux1 image

.github/workflows/build-macos-openssl.yml
Homebrew's plan is to switch to /opt/homebrew for arm64 macOS.
=> use diff openssldir on macOS for x86_64 and arm64

.github/workflows/build-docker-images.yml, cryptography-manylinux/Dockerfile-manylinux2014
We're now not far from dropping manylinux1. We should start doing manylinux2014 builds to see what percentage of our users have pip new enough to pull that.
Separately we should consider advocating that pip put in logic for manylinux2019 now even though the spec hasn't been defined and won't be for awhile specifically to get ahead of this tag issue.
=> add manylinux2014 x86-64 image

runners/debian/Dockerfile
Once a debian version is released `/etc/debian_release` contains a version, so the `stretch` search here always returned false.
=> switch to searching on os-release

.github/workflows/build-docker-images.yml, cryptography-manylinux/Dockerfile-manylinux, cryptography-manylinux/install_libffi.sh
`manylinux1/2010/2014` are CentOS-based but `2_24` runs Debian 9.
This is why this patch switches over to using APT conditionally
to install `prelink` with an OS-specific package manager.
Also, this change resorts to calling the executable scripts
directly letting the runtime consult with the shebang and use the
appropriate interpreter.
Old CentOS-based images have `sh` pointing to `bash` while in Debian
it actually points to `sh`. This is a side-effect that the old image
used to rely on and it does not work anymore for `manylinux_2_24`.
One way would be to change `s/sh/bash` in the dockerfile but I chose
to rely on the existing shebang comments that already point to it but
are ignored when the interpreter is stated explicitly.
Fixes #339
=> Add `manylinux_2_24` images to the build matrix

.github/workflows/build-docker-images.yml, cryptography-manylinux/Dockerfile-manylinux, cryptography-manylinux/install_openssl.sh
The instruction `ARG RELEASE` was only present before the `FROM` line
making it out of scope. This change exposes it to the main image
build stage.
Note that this change makes the `${RELEASE}` env var available in the
runtime of each `RUN` instruction which may cause unintended
side-effects whenever any underlying tooling depends on the value in
this variable.
It is known that the underlying build scripts of OpenSSL rely on the
`${RELEASE}` environment variable and if it's suddenly available in
the env, it goes crazy when the value is illegal.
In particular, it errors out with the following message:
```console
Operating system: x86_64-whatever-Linux
This system (Linux) is not supported. See file INSTALL for details.
```
This is why the change is accompanied with `unset RELEASE` patches to …
=> Expose `RELEASE` build env var in the stage scope

runners/alpine/Dockerfile
github action wants a tar with `--posix`. The default tar on alpine is BusyBox which doesn't support that flag.
=> Install tar in the alpine container

.github/workflows/build-docker-images.yml, cryptography-manylinux/Dockerfile-manylinux
This should get everything going once musllinux is available from https://github.com/pypa/manylinux/pull/1135
I should caveat this PR by saying that afaik this is my first day touching anything in the python ecosystem so apologies if this is dumb lol
Also I kinda anticipate the pypy shuffling in cryptography-manylinux/Dockerfile-manylinux will not pass review but I included it in the off chance no one cares (why is pypy used in the pyca/cryptography builds?) or if any one wants to test building Alpine cryptography wheels with musllinux. Here's how I did that:
```shell
git clone git@github.com:pypa/manylinux
pushd manylinux
MANYLINUX_BUILD_FRONTEND=docker POLICY="musllinux_1_1" PLATFORM="x86_64" COMMIT_SHA="HEAD" ./build.sh
popd
git clone git@github.com:pyca/infra
pushd infra
docker build …
```
=> preparations for musllinux

.github/workflows/build-docker-images.yml
100% untested, based on https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml
=> Attempt to use sigstore to sign our docker images

.github/workflows/build-docker-images.yml, runners/rhel/Dockerfile
These containers can replace rhel8 when we drop 3.6, although right now they demonstrate two bugs in Red Hat's OpenSSL patches (see: https://github.com/pyca/cryptography/issues/6962)
=> build centos stream containers (including fips variant)

runners/alpine/Dockerfile, runners/debian/Dockerfile, runners/fedora/Dockerfile, runners/rhel/Dockerfile, runners/ubuntu/Dockerfile
Install it at test-time so we can pin versions
=> Stop pre-installing tox and coverage into docker containers

terraform/cloudinit.tf, terraform/helm.tf
This properly provisions new worker nodes and resizes the partition and disables the pod security policy in cert-manager that didn't do anything anyway since it's deprecated and removed in k8s 1.25+.
An upcoming PR will migrate us to k8s 1.25.x
=> terraform fixes

runners/rhel/Dockerfile
this means tox will be installed with python 3.8, doesn't affect how tests are run
=> On RHEL8, create the venv with python 3.8

runners/alpine/Dockerfile, runners/debian/Dockerfile, runners/ubuntu/Dockerfile
But only the ones where _this_ is the current failure in https://github.com/pyca/cryptography/pull/8936, there's other that require more debugging (and which I'll eventually send a follow-up PR here for)
=> Install llvm-tools-preview in some of the Docker containers

terraform/runnerdeployment.yml
free tier disk IO is slow, let's just not use the disk
=> use a ramdisk for the docker volume mount on our k8s cluster

cryptography-linux/Dockerfile, runners/alpine/Dockerfile
=> Revert "use gcompat from source to work around lack of fcntl64 release"

.github/workflows/build-docker-images.yml, .github/workflows/build-static-node.yml, cryptography-linux/Dockerfile, runners/alpine/Dockerfile, staticnode/Dockerfile, staticnode/Dockerfile-test, staticnode/node-version.sh
also copy it to /staticnode on manylinux2014 and alpine builders
The static-nodejs containers have already been pushed from a branch, but this PR should demonstrate the successful building of the manylinux and alpine containers.
Future improvements (follow up PR preferably due to the insanely painful cycle times on this):
* Figure out how to specify the node version tag in just one place rather than in every build arg.
* Use multi-stage builds to shrink the static-nodejs containers to just containing /out.
* Add the same hash checking we use for OpenSSL when building.
=> build static node.js for manylinux2014 x86_64 and arm64

.github/workflows/build-docker-images.yml
Don't merge until cryptography 43 is released
=> Remove buster image, it is EOL

.github/workflows/build-windows-openssl.yml, windows/openssl/build_openssl_win32.bat, windows/openssl/build_openssl_win64.bat
This will speed us up significantly. However, it also increases the size of the static `.lib` files. This may just be an artifact of the order in which the linker does things, but we can verify everything behaves as expected in our test suite on the cryptography side once it merges as well.
=> try using jom for parallel windows compilation

runners/alpine/Dockerfile
since we now use our own static node we hopefully do not need this, but we'll find out I guess.
=> remove gcompat

.github/workflows/build-docker-images.yml, cryptography-linux/Dockerfile
This PR adds support for the ppc64le (PowerPC 64-bit Little Endian) architecture across multiple GitHub Actions workflows and Docker build configurations.
🔧 Changes made:
1. Wheel Builder Workflow (build-docker-images.yml)
Added two new manylinux containers for ppc64le:
manylinux2014:ppc64le
manylinux_2_28:ppc64le
2. Docker Image Builder Workflow (build-docker-images.yml)
Added definitions to build:
Runner base image: cryptography-runner-ubuntu-24.04:ppc64le
Wheel images: manylinux2014:ppc64le, manylinux_2_28:ppc64le
3. Dockerfile Update (cryptography-linux/Dockerfile)
Extended platform-specific install block to recognize ppc64le.
=> Add ppc64le support to Docker images
