README.md, build-images.py
Also line wrap, and use absolute paths
=> Expand docs a bit.

caddy/Caddyfile
=> the caddy container should also proxy our website

ansible/systemd/jenkins.service
=> increase jenkins session timeout to one week

ansible/playbook.yml
As is our custom with ansible scripts this is tested by me running it and confirming it works properly.
=> init a single node docker swarm

caddy/Dockerfile
=> switch caddy to nobody user

config.json, runners/ubuntu-rolling/Dockerfile, runners/xenial/Dockerfile
`rolling` is the latest release. `xenial` is, of course, the current LTS, which we could also get with `ubuntu:lts` if we wanted.
=> add ubuntu xenial and ubuntu rolling containers

ansible/systemd/jenkins.service
=> Revert "Remove --read-only from jenkins, as an expirement"

hubot/Dockerfile, jenkins/Dockerfile, runners/jessie-libressl/Dockerfile, runners/jessie/Dockerfile, runners/sid/Dockerfile, runners/stretch/Dockerfile, runners/ubuntu-rolling/Dockerfile, runners/wheezy/Dockerfile, runners/xenial/Dockerfile
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#apt-get
=> Adhere to dockerfile best pracices with respect to apt-get:

runners/fedora/Dockerfile, runners/sid/Dockerfile, runners/stretch/Dockerfile, runners/wheezy/Dockerfile
I've put them as separate layers in the dockerfile to make them more obvious and extraction easier when the time comes
=> workaround for https://issues.jenkins-ci.org/browse/JENKINS-40101

config.json, cryptography-manylinux1/Dockerfile
=> fix ARCH being passed to the install openssl script properly

cryptography-manylinux1/install_openssl.sh
should not be merged until we inspect the CI output 😄
=> use config, which selects the right Configure type and sets noexecstack

runners/fedora/Dockerfile
because @tomprince told me too
=> use a different repo for fedora

jenkins/Dockerfile
=> Switch to new upstream jenkins docker image

external-projects/Jenkinsfile-brotlipy-wheel-builder
cc @Lukasa. Sample output https://ci.cryptography.io/blue/organizations/jenkins/external-projects%2Fbrotlipy-wheel-builder/detail/brotlipy-wheel-builder/11/
=> add jenkinsfile for brotlipy wheel builder

runners/alpine/Dockerfile
Refs: https://github.com/pyca/cryptography/issues/4038
=> Try switching teh alpine runner back to latest

caddy/Caddyfile, caddy/Dockerfile, caddy/tls.conf
Not tested.
Requires we be using the latest caddy
=> Use new import syntax in the Caddyfile

caddy/Caddyfile
=> set expect ct on all requests

external-projects/Jenkinsfile-brotlipy-wheel-builder
=> Add py3.7 support to brotlipy wheel builder

external-projects/Jenkinsfile-argon2cffi-wheel-builder
=> Add py3.7 support to argon2cffi wheel builder

external-projects/Jenkinsfile-cffi-wheel-builder
=> Add py3.7 support to cffi wheel builder

external-projects/Jenkinsfile-pyyaml-wheel-builder
=> Add 3.7 support to pyyaml wheel builder

external-projects/Jenkinsfile-brotlipy-wheel-builder
manylinux1 no longer supports py33
=> drop py33 manylinux1 wheels for brotlipy

external-projects/Jenkinsfile-argon2cffi-wheel-builder
=> switch argon2_cffi to use py_limited_api

external-projects/Jenkinsfile-argon2cffi-wheel-builder
=> much simpler py_limited_api

runners/alpine/Dockerfile, runners/centos7/Dockerfile, runners/debian/Dockerfile, runners/fedora/Dockerfile, runners/ubuntu/Dockerfile
This will make our lives much simpler. If we complete the switch we can remove these lines and just change the ARG values away from jenkins.
=> add a travis user

azure-pipelines.yml, windows/openssl/Dockerfile, windows/openssl/build_openssl.bat, windows/openssl/build_openssl_win32_2010.bat, windows/openssl/build_openssl_win32_2015.bat, windows/openssl/build_openssl_win64_2010.bat, windows/openssl/build_openssl_win64_2015.bat, windows/openssl/install_tools.ps1, windows/openssl/setup.bat
=> windows openssl docker builders

azure-pipelines.yml, windows/py3/Dockerfile, windows/py3/install_python.ps1, windows/py34/Dockerfile, windows/py34/install_compiler.ps1, windows/py34/install_python.ps1
this is py3.5+. py 3.4 comes in a separate image since it has a different compiler
=> add py3 builder

azure-pipelines.yml, windows/py35/Dockerfile, windows/py35/install_python.ps1
2017 should work but python 3.5 can't seem to find it so whatever.
=> add a python 3.5 builder that just uses vs 2015

azure-pipelines.yml, cryptography-manylinux2010/Dockerfile, cryptography-manylinux2010/install_libffi.sh, cryptography-manylinux2010/install_openssl.sh, cryptography-manylinux2010/install_virtualenv.sh
=> manylinux2010 container

azure-pipelines.yml, runners/centos8/Dockerfile
Before this can be merged, @reaperhulk can you please create a repo for it?
=> Added a runner for CentOS 8

.github/workflows/build-macos-openssl.yml, .github/workflows/build-windows-openssl.yml
Also rename windows OpenSSL build file
=> Rebuild macOS and Windows openssl on version change

.github/workflows/build-macos-openssl.yml, .github/workflows/build-windows-openssl.yml, cryptography-manylinux/install_openssl.sh, cryptography-manylinux/openssl-version.sh, windows/openssl/build_openssl_win32_2010.bat, windows/openssl/build_openssl_win32_2019.bat, windows/openssl/build_openssl_win64_2010.bat, windows/openssl/build_openssl_win64_2019.bat
Let's see if the env var propagates into the windows batch sub-scripts...
=> de-duplicate openssl build flags

runners/alpine/Dockerfile
we didn't test with py2 on alpine anyway.
=> alpine no longer has py2

.github/workflows/build-docker-images.yml, runners/centos8/Dockerfile
literally the only difference is /etc/system-fips but whatever
=> add centos8 fips runner

.github/workflows/build-docker-images.yml
=> push to docker hub on cron as well as push to master

README.md
=> explain what to do for new images

.github/workflows/build-docker-images.yml
=> switch to official github action for buildx

cryptography-manylinux/Dockerfile-manylinux2010, cryptography-manylinux/Dockerfile-manylinux2014, cryptography-manylinux/Dockerfile-manylinux2014_aarch64, runners/alpine/Dockerfile, runners/centos8/Dockerfile, runners/debian/Dockerfile, runners/fedora/Dockerfile, runners/ubuntu/Dockerfile
this shaves hundreds of MBs of docs from the container image
=> Use the minimal rust install profile

.github/workflows/build-docker-images.yml
=> push with standard github actions token

cryptography-manylinux/Dockerfile-manylinux
libffi for all aarch64, miniature american flags for x86_64
=> complexify the package installs

.github/workflows/build-macos-openssl.yml
Example: https://github.com/messense/infra/actions/runs/666770527
I'll revert the second commit if this PR is accepted.
=> Create macOS universal2 OpenSSL using lipo

runners/alpine/Dockerfile, runners/fedora/Dockerfile
It's not the default and its broken
=> Switch away from libressl on alpine

.github/workflows/build-docker-images.yml
=> Revert "Attempt to use sigstore to sign our docker images"

.github/workflows/build-docker-images.yml
=> Shorten job names

cryptography-linux/openssl-version.sh
This reverts commit 47ba33d154278c1205339636e11967e48b617b2c.
=> Revert "update to 3.0.6 (#420)"

cryptography-linux/openssl-version.sh
merge when we're close to ready for 40.0.0
=> openssl 3.1.0

.github/workflows/build-docker-images.yml
=> stop building 2_24 manylinux images

runners/rhel/Dockerfile
Per https://bugzilla.redhat.com/show_bug.cgi?id=2208724 that's how to enable the proper behaviors in CentOS 9 Stream.
=> run update-crypto-policies --set FIPS for centos containers

cryptography-linux/Dockerfile, runners/alpine/Dockerfile
=> use gcompat from source to work around lack of fcntl64 release

cryptography-linux/Dockerfile, runners/alpine/Dockerfile
verified that this works on aarch64 but untested on x86_64
we may also still not be able to upgrade to node20 because of our glibc versions on manylinux2014.
=> gcompat again

.github/workflows/build-docker-images.yml
This is better than us needing to manually bump
=> Use rolling for the arm64 image

.github/workflows/build-docker-images.yml
=> Simplify configuration of node arch

cryptography-linux/install_openssl.sh
=> Allow redirects when downloading openssl

cryptography-linux/Dockerfile
=> We no longer need libffi-devel in manylinux containers

.github/workflows/terraform.yml
its no longer in the base image
=> install terraform in GHA

.github/workflows/build-docker-images.yml
=> Correct subject-name in docker attestations

.github/workflows/build-docker-images.yml
we want the name without the tag
=> use the correct image name when attesting
